# Generated by Django 6.0.4 on 2026-04-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_product2category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
