# Generated by Django 6.0.4 on 2026-04-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_shippingaddress2user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
